version: "3.7"
services:
  kml: 
    build: ./app
    container_name: kml
    ports:
      - "8501:8501"
    networks:
      website_network:
        aliases:
          - red
networks:
  website_network:
    name: red_network